/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/blocks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar blocos
     * @description Retorna todos os blocos do condomínio ativo.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.BlockResponse"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Criar bloco
     * @description Cria um novo bloco no condomínio ativo.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dados do bloco */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.CreateBlockRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.BlockResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blocks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar bloco por ID
     * @description Retorna um bloco pelo seu UUID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Bloco */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.BlockResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Deletar bloco
     * @description Remove um bloco e todas as suas unidades (CASCADE).
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Bloco */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Atualizar bloco
     * @description Atualiza nome e descrição de um bloco. Apenas campos enviados são alterados.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Bloco */
          id: string;
        };
        cookie?: never;
      };
      /** @description Dados atualizados */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateBlockRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.BlockResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/common-areas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar áreas comuns
     * @description Retorna todas as áreas comuns do condomínio ativo.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.CommonAreaResponse"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Criar área comum
     * @description Cria uma nova área comum no condomínio ativo.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dados da área comum */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.CreateCommonAreaRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.CommonAreaResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/common-areas/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar área comum por ID
     * @description Retorna uma área comum pelo seu UUID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Área Comum */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.CommonAreaResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Deletar área comum
     * @description Remove uma área comum. Tickets vinculados têm common_area_id zerado (ON DELETE SET NULL).
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Área Comum */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Atualizar área comum
     * @description Atualiza nome e tipo de uma área comum. Apenas campos enviados são alterados.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Área Comum */
          id: string;
        };
        cookie?: never;
      };
      /** @description Dados atualizados */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateCommonAreaRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.CommonAreaResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/condos/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar condomínios do gestor
     * @description Retorna todos os condomínios acessíveis ao usuário autenticado com a respectiva role. Super admins recebem todos os condomínios com role "super_admin".
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Lista de condomínios com role */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.CondoMeResponse"][];
          };
        };
        /** @description Não autorizado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Erro interno */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/condos/{id}/invite-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar tokens de convite
     * @description Retorna os tokens de convite do condomínio com paginação. Por padrão exclui revogados.
     */
    get: {
      parameters: {
        query?: {
          /** @description Limite de resultados (default: 50, max: 100) */
          limit?: number;
          /** @description Offset para paginação (default: 0) */
          offset?: number;
          /** @description Incluir tokens revogados (default: false) */
          include_revoked?: boolean;
        };
        header?: never;
        path: {
          /** @description UUID do Condomínio */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.InviteTokenResponse"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Gerar token de convite
     * @description Gera um token de convite para o condomínio. Tipo 'invite' é uso único (7 dias). Tipo 'permanent' é multi-uso (1 ano), ideal para QR impresso.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Condomínio */
          id: string;
        };
        cookie?: never;
      };
      /** @description Tipo do token */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.GenerateTokenRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.InviteTokenResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/condos/{id}/invite-tokens/{tid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revogar token de convite
     * @description Revoga um token de convite. Tokens revogados não podem mais ser usados. Idempotente — revogar um token já revogado retorna 204.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Condomínio */
          id: string;
          /** @description UUID do Token */
          tid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check API health
     * @description Returns the health status of the API and connected services (DB, AI, etc.)
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/managers/me/telegram": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Registrar Telegram do gestor
     * @description Vincula o chat_id do Telegram ao gestor autenticado para receber notificações.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Chat ID do Telegram */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.RegisterTelegramRequest"];
        };
      };
      responses: {
        /** @description telegram registered */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Não autorizado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Erro interno */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/residents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar residentes
     * @description Retorna todos os residentes do condomínio ativo.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Registrar residente
     * @description Registra um novo residente com status PENDING. unit_id é opcional — resolvido ao final do onboarding.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dados do residente */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.CreateResidentRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/residents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar residente por ID
     * @description Retorna um residente pelo seu UUID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Residente */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Atualizar residente
     * @description Atualiza dados do residente. Apenas campos enviados são alterados.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Residente */
          id: string;
        };
        cookie?: never;
      };
      /** @description Dados atualizados */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateResidentRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/residents/{id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Aprovar residente
     * @description Aprova um residente com status PENDING, alterando para ACTIVE e notificando via Telegram.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Residente */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/residents/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Rejeitar residente
     * @description Rejeita um residente com status PENDING, alterando para INACTIVE e notificando via Telegram.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Residente */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/residents/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Atualizar status do residente
     * @description Altera o status de um residente (ACTIVE, INACTIVE, PENDING).
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Residente */
          id: string;
        };
        cookie?: never;
      };
      /** @description Novo status */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateResidentStatusRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.ResidentResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar tickets
     * @description Retorna uma lista de tickets filtrados por status ou prioridade para o condomínio ativo.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filtrar por status (open, in_progress, resolved, closed) */
          status?: string;
          /** @description Filtrar por prioridade (low, medium, high) */
          priority?: string;
          /** @description Filtrar por protocolo humano (ex: TKT-2026-00001) */
          protocol?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketResponse"][];
          };
        };
        /** @description Formato de protocolo inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Não autorizado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Erro interno */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Criar um novo ticket
     * @description Cria um ticket de manutenção vinculado a um morador.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dados do ticket */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.CreateTicketRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketResponse"];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Não autorizado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Erro interno */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Exportar tickets em CSV
     * @description Exporta tickets do condomínio em CSV para prestação de contas. Manager-only. Timestamps em UTC (limitação MVP).
     */
    get: {
      parameters: {
        query?: {
          /** @description Filtrar por status (open, in_progress, resolved, closed) */
          status?: string;
          /** @description Filtrar por prioridade (low, medium, high, urgent) */
          priority?: string;
          /** @description Filtrar por protocolo (ex: TKT-2026-00001) */
          protocol?: string;
          /** @description Data inicial inclusiva (YYYY-MM-DD, UTC) */
          created_from?: string;
          /** @description Data final inclusiva (YYYY-MM-DD, UTC) */
          created_to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description CSV attachment */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/csv": string;
          };
        };
        /** @description Parâmetro inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/csv": {
              [key: string]: string;
            };
          };
        };
        /** @description Acesso negado */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/csv": {
              [key: string]: string;
            };
          };
        };
        /** @description Erro interno */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/csv": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar ticket por ID
     * @description Retorna os detalhes de um único ticket se pertencer ao condomínio do usuário.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Ticket */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketResponse"];
          };
        };
        /** @description ID inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Ticket não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/{id}/assign": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Assumir ticket (auto-atribuição)
     * @description O manager autenticado assume o ticket. Status muda para in_progress se estava open.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Ticket */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketResponse"];
          };
        };
        /** @description ID inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Ticket não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/tickets/{id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Adicionar comentário ao ticket
     * @description Adiciona um comentário como evento ao ticket especificado.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Ticket */
          id: string;
        };
        cookie?: never;
      };
      /** @description Texto do comentário */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.AddCommentRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketEventResponse"];
          };
        };
        /** @description ID inválido ou texto vazio */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Ticket não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/{id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar eventos do ticket
     * @description Retorna a timeline de eventos de um ticket ordenada cronologicamente.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Ticket */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.TicketEventResponse"][];
          };
        };
        /** @description ID inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Ticket não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Atualizar status do ticket
     * @description Altera o status de um ticket existente.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID do Ticket */
          id: string;
        };
        cookie?: never;
      };
      /** @description Novo status */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateTicketStatusRequest"];
        };
      };
      responses: {
        /** @description Status atualizado */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Requisição inválida */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Ticket não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/units": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar unidades
     * @description Retorna unidades do condomínio ativo. Filtra por bloco via query param.
     */
    get: {
      parameters: {
        query?: {
          /** @description UUID do Bloco para filtrar */
          block_id?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.UnitResponse"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Criar unidade
     * @description Cria uma unidade dentro de um bloco do condomínio ativo.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dados da unidade */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.CreateUnitRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.UnitResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar unidade por ID
     * @description Retorna uma unidade pelo seu UUID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Unidade */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.UnitResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Deletar unidade
     * @description Remove uma unidade. Residentes vinculados ficam com unit_id = NULL.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Unidade */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Atualizar unidade
     * @description Atualiza número e andar de uma unidade. Apenas campos enviados são alterados.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID da Unidade */
          id: string;
        };
        cookie?: never;
      };
      /** @description Dados atualizados */
      requestBody: {
        content: {
          "application/json": components["schemas"]["internal_adapters_http.UpdateUnitRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["internal_adapters_http.UnitResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "internal_adapters_http.AddCommentRequest": {
      text?: string;
    };
    "internal_adapters_http.BlockResponse": {
      condo_id?: string;
      created_at?: string;
      description?: string;
      id?: string;
      name?: string;
      updated_at?: string;
    };
    "internal_adapters_http.CommonAreaResponse": {
      condo_id?: string;
      created_at?: string;
      id?: string;
      name?: string;
      type?: string;
      updated_at?: string;
    };
    "internal_adapters_http.CondoMeResponse": {
      condo_id?: string;
      condo_name?: string;
      condo_slug?: string;
      role?: string;
    };
    "internal_adapters_http.CreateBlockRequest": {
      description?: string;
      name?: string;
    };
    "internal_adapters_http.CreateCommonAreaRequest": {
      name?: string;
      /** @description elevator | pool | lobby | garage | gym | other (default) */
      type?: string;
    };
    "internal_adapters_http.CreateResidentRequest": {
      email?: string;
      name?: string;
      phone?: string;
      /** @description opcional — resolvido ao final do onboarding */
      unit_id?: string;
    };
    "internal_adapters_http.CreateTicketRequest": {
      /** @description opcional — UUID da área comum; sobrescreve Location e LocationRef */
      common_area_id?: string;
      description?: string;
      /** @description "common_area" | "unit" (default: common_area) */
      location?: string;
      /** @description ex: "Elevador B", "Piscina" */
      location_ref?: string;
      priority?: string;
      resident_id?: string;
      title?: string;
    };
    "internal_adapters_http.CreateUnitRequest": {
      block_id?: string;
      floor?: number;
      number?: string;
    };
    "internal_adapters_http.GenerateTokenRequest": {
      /** @description "invite" | "permanent" */
      type?: string;
    };
    "internal_adapters_http.InviteTokenResponse": {
      condo_id?: string;
      created_at?: string;
      expires_at?: string;
      id?: string;
      link?: string;
      max_uses?: number;
      revoked_at?: string;
      token?: string;
      type?: string;
      use_count?: number;
    };
    "internal_adapters_http.RegisterTelegramRequest": {
      chat_id?: number;
    };
    "internal_adapters_http.ResidentResponse": {
      condo_id?: string;
      created_at?: string;
      email?: string;
      id?: string;
      name?: string;
      phone?: string;
      status?: string;
      unit_id?: string;
      updated_at?: string;
    };
    "internal_adapters_http.TicketEventResponse": {
      actor_id?: string;
      actor_type?: string;
      created_at?: string;
      event_type?: string;
      id?: string;
      payload?: {
        [key: string]: unknown;
      };
      ticket_id?: string;
    };
    "internal_adapters_http.TicketResponse": {
      /** @description user_id do manager atribuído */
      assigned_to?: string;
      block_name?: string;
      common_area_id?: string;
      common_area_name?: string;
      condo_id?: string;
      created_at?: string;
      description?: string;
      id?: string;
      location?: string;
      location_ref?: string;
      priority?: string;
      /** @description TKT-YYYY-NNNNN — sequencial por condo, reset anual */
      protocol?: string;
      resident_id?: string;
      resident_name?: string;
      status?: string;
      title?: string;
      unit_number?: string;
      updated_at?: string;
    };
    "internal_adapters_http.UnitResponse": {
      block_id?: string;
      condo_id?: string;
      created_at?: string;
      floor?: number;
      id?: string;
      number?: string;
      updated_at?: string;
    };
    "internal_adapters_http.UpdateBlockRequest": {
      description?: string;
      name?: string;
    };
    "internal_adapters_http.UpdateCommonAreaRequest": {
      name?: string;
      type?: string;
    };
    "internal_adapters_http.UpdateResidentRequest": {
      email?: string;
      name?: string;
      phone?: string;
      status?: string;
      unit_id?: string;
    };
    "internal_adapters_http.UpdateResidentStatusRequest": {
      status?: string;
    };
    "internal_adapters_http.UpdateTicketStatusRequest": {
      status?: string;
    };
    "internal_adapters_http.UpdateUnitRequest": {
      floor?: number;
      number?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
