import type { ActivityEvent } from "./types";

const NOW = Date.parse("2026-05-14T12:00:00Z");
function ago(minutes: number): string {
  return new Date(NOW - minutes * 60 * 1000).toISOString();
}

export const FIXTURES: ActivityEvent[] = [
  {
    id: "ev-1",
    kind: "ticket_new",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Novo chamado urgente: Câmera de entrada offline",
    subtitle: "Residencial Jardins · TKT-2026-101 · Portaria",
    resourceRef: { type: "ticket", ticketId: "tk-101" },
    priority: "urgent",
    occurredAt: ago(15),
    readAt: null,
  },
  {
    id: "ev-2",
    kind: "ticket_new",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Novo chamado: Elevador parado no 8º andar",
    subtitle: "Residencial Jardins",
    resourceRef: { type: "ticket", ticketId: "tk-102" },
    priority: "medium",
    occurredAt: ago(45),
    readAt: null,
  },
  {
    id: "ev-3",
    kind: "approval",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Aprovação pendente: Lucas Ferreira (Bloco B, 203)",
    subtitle: "Residencial Jardins · Verificar identidade",
    resourceRef: { type: "resident_approval", residentId: "res-501" },
    occurredAt: ago(120),
    readAt: null,
  },
  {
    id: "ev-4",
    kind: "ticket_comment",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Novo comentário em TKT-2026-041",
    subtitle: "Residencial Jardins · 'Obrigado pelo retorno rápido'",
    resourceRef: { type: "ticket", ticketId: "tk-041" },
    occurredAt: ago(180),
    readAt: ago(60),
  },
  {
    id: "ev-5",
    kind: "ticket_new",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Novo chamado: Vazamento na 2ª garagem G1",
    subtitle: "Residencial Jardins",
    resourceRef: { type: "ticket", ticketId: "tk-103" },
    priority: "medium",
    occurredAt: ago(240),
    readAt: ago(120),
  },
  {
    id: "ev-6",
    kind: "status_change",
    condoId: "c-vilamar",
    condoName: "Vila Mar",
    title: "TKT-2026-038 → Em andamento",
    subtitle: "Vila Mar",
    resourceRef: { type: "ticket", ticketId: "tk-038" },
    occurredAt: ago(300),
    readAt: ago(60),
  },
  {
    id: "ev-7",
    kind: "approval",
    condoId: "c-vilamar",
    condoName: "Vila Mar",
    title: "Aprovação pendente: Maria Souza (Bloco A, 12)",
    subtitle: "Vila Mar",
    resourceRef: { type: "resident_approval", residentId: "res-502" },
    occurredAt: ago(360),
    readAt: null,
  },
  {
    id: "ev-8",
    kind: "ticket_new",
    condoId: "c-vilamar",
    condoName: "Vila Mar",
    title: "Novo chamado: Portão da garagem com ruído",
    subtitle: "Vila Mar",
    resourceRef: { type: "ticket", ticketId: "tk-104" },
    priority: "low",
    occurredAt: ago(420),
    readAt: ago(60),
  },
  {
    id: "ev-9",
    kind: "ticket_comment",
    condoId: "c-vilamar",
    condoName: "Vila Mar",
    title: "Novo comentário em TKT-2026-032",
    subtitle: "Vila Mar",
    resourceRef: { type: "ticket", ticketId: "tk-032" },
    occurredAt: ago(540),
    readAt: ago(180),
  },
  {
    id: "ev-10",
    kind: "ticket_new",
    condoId: "c-vilamar",
    condoName: "Vila Mar",
    title: "Chamado urgente: Falta d'água no bloco C",
    subtitle: "Vila Mar · TKT-2026-105 · Hidráulica",
    resourceRef: { type: "ticket", ticketId: "tk-105" },
    priority: "urgent",
    occurredAt: ago(720),
    readAt: ago(360),
  },
  {
    id: "ev-11",
    kind: "status_change",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "TKT-2026-030 → Resolvido",
    subtitle: "Residencial Jardins",
    resourceRef: { type: "ticket", ticketId: "tk-030" },
    occurredAt: ago(900),
    readAt: ago(720),
  },
  {
    id: "ev-12",
    kind: "ticket_new",
    condoId: "c-jardins",
    condoName: "Residencial Jardins",
    title: "Novo chamado: Lâmpada queimada na escada",
    subtitle: "Residencial Jardins",
    resourceRef: { type: "ticket", ticketId: "tk-106" },
    priority: "low",
    occurredAt: ago(1440),
    readAt: ago(60),
  },
];
